name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    if: startsWith(github.event.head_commit.message, 'v') # 仅当提交消息以 v 开头时运行
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install

      # 4. 构建 Electron 应用
      - name: Build Application
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build

      # 5. 上传构建产物到 Release
      - name: Publish to GitHub Releases
        uses: samuelmeuli/action-electron-builder@v2
        with:
          release: github
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
