name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Build and Release Electron App
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 创建Release

      # Windows构建
      - name: Build Windows App
        if: matrix.os == 'windows-latest'
        run: yarn build:win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # macOS构建
      - name: Build macOS App
        if: matrix.os == 'macos-latest'
        run: yarn electron-builder build --mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Linux构建
      - name: Build Linux App
        if: matrix.os == 'ubuntu-latest'
        run: yarn electron-builder build --linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # 将生成的文件作为artifacts上传
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nb_music-${{ matrix.os }}
          path: dist/**/*

  